import React, { useState, useMemo } from 'react';
import { BookOpen, Search, X, ChevronDown, ChevronUp, Info } from 'lucide-react';

export interface GlossaryTerm {
  id: string;
  term: string;
  definition: string;
  category: 'calculator' | 'recommendation' | 'metrics' | 'general';
  relatedTerms?: string[];
  example?: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'carbon-footprint',
    term: 'Carbon Footprint',
    definition: 'The total amount of greenhouse gases (including carbon dioxide and methane) generated by an event, measured in kilograms or tonnes of CO2 equivalent (CO2e). This includes emissions from venue energy use, food and beverage production, attendee transportation, and materials.',
    category: 'calculator',
    relatedTerms: ['emission-breakdown', 'carbon-offsetting', 'greenhouse-gases'],
    example: 'A 100-person conference with air travel, meat-heavy catering, and printed materials might have a carbon footprint of 5,000 kg CO2e.'
  },
  {
    id: 'carbon-offsetting',
    term: 'Carbon Offsetting',
    definition: 'The practice of compensating for carbon emissions by funding projects that reduce or remove an equivalent amount of CO2 from the atmosphere. Common offset projects include reforestation, renewable energy installations, and methane capture programs.',
    category: 'recommendation',
    relatedTerms: ['carbon-footprint', 'carbon-credits', 'net-zero'],
    example: 'Purchasing carbon credits to offset 2 tonnes of CO2e from your event by funding a wind farm project.'
  },
  {
    id: 'sustainability-score',
    term: 'Sustainability Score (Green Score)',
    definition: 'A comprehensive rating from 0-100 that evaluates the overall environmental performance of an event. The score considers carbon emissions, water usage, waste generation, and sustainable practices across all event categories. Higher scores indicate better environmental performance.',
    category: 'metrics',
    relatedTerms: ['carbon-footprint', 'environmental-impact', 'benchmarking'],
    example: 'An event with renewable energy, plant-based catering, public transport access, and zero waste practices might achieve a Platinum score of 95/100.'
  },
  {
    id: 'emission-breakdown',
    term: 'Emission Breakdown',
    definition: 'A detailed analysis showing how carbon emissions are distributed across different event categories: venue energy (heating, cooling, lighting), food and beverage production, attendee transportation, and materials (printing, swag, decorations). This helps identify the biggest sources of emissions.',
    category: 'calculator',
    relatedTerms: ['carbon-footprint', 'scope-emissions', 'hotspot-analysis'],
    example: 'For a typical conference: Transport 45%, Food & Beverage 30%, Venue 20%, Materials 5%.'
  },
  {
    id: 'greenhouse-gases',
    term: 'Greenhouse Gases (GHG)',
    definition: 'Gases that trap heat in the atmosphere, contributing to global warming. The main greenhouse gases from events include carbon dioxide (CO2), methane (CH4), and nitrous oxide (N2O). All are converted to CO2 equivalent (CO2e) for standardized measurement.',
    category: 'general',
    relatedTerms: ['carbon-footprint', 'co2-equivalent'],
    example: 'Methane from food waste has 25 times the warming potential of CO2 over 100 years.'
  },
  {
    id: 'co2-equivalent',
    term: 'CO2 Equivalent (CO2e)',
    definition: 'A standardized unit that expresses the impact of different greenhouse gases in terms of the amount of CO2 that would have the same global warming potential. This allows for consistent comparison and calculation.',
    category: 'calculator',
    relatedTerms: ['greenhouse-gases', 'carbon-footprint'],
    example: '1 kg of methane = 25 kg CO2e; 1 kg of nitrous oxide = 298 kg CO2e.'
  },
  {
    id: 'carbon-credits',
    term: 'Carbon Credits',
    definition: 'Tradable certificates representing the removal or reduction of one tonne of CO2e from the atmosphere. Organizations can purchase credits to offset their emissions. Credits are verified by standards like Gold Standard or Verified Carbon Standard (VCS).',
    category: 'recommendation',
    relatedTerms: ['carbon-offsetting', 'net-zero'],
    example: 'Gold Standard carbon credits typically cost $25-50 per tonne CO2e.'
  },
  {
    id: 'scope-emissions',
    term: 'Scope 1, 2, 3 Emissions',
    definition: 'A framework for categorizing emissions: Scope 1 (direct emissions from owned sources), Scope 2 (indirect emissions from purchased energy), Scope 3 (all other indirect emissions in the value chain, including attendee travel and supply chain).',
    category: 'calculator',
    relatedTerms: ['emission-breakdown', 'carbon-footprint'],
    example: 'For events, most emissions are Scope 3 (attendee travel, catering supply chain).'
  },
  {
    id: 'net-zero',
    term: 'Net Zero',
    definition: 'Achieving a balance between the amount of greenhouse gas emissions produced and the amount removed from the atmosphere. This is accomplished by reducing emissions as much as possible and offsetting remaining emissions.',
    category: 'recommendation',
    relatedTerms: ['carbon-offsetting', 'carbon-neutral'],
    example: 'A net-zero event reduces emissions by 80% through sustainable practices and offsets the remaining 20%.'
  },
  {
    id: 'benchmarking',
    term: 'Industry Benchmarking',
    definition: 'Comparing your event\'s environmental performance against industry standards and similar events. This helps identify whether your emissions are above or below average and where improvements are needed.',
    category: 'metrics',
    relatedTerms: ['sustainability-score', 'percentile-ranking'],
    example: 'Your event is in the top 25% of similar conferences for sustainability performance.'
  },
  {
    id: 'water-footprint',
    term: 'Water Footprint',
    definition: 'The total volume of freshwater used directly and indirectly to produce goods and services for an event. This includes water for food production, venue operations, and manufacturing of materials.',
    category: 'calculator',
    relatedTerms: ['environmental-impact', 'resource-consumption'],
    example: 'A meat-heavy meal requires 10x more water than a plant-based meal.'
  },
  {
    id: 'waste-diversion',
    term: 'Waste Diversion Rate',
    definition: 'The percentage of waste diverted from landfills through recycling, composting, or reuse. A higher diversion rate indicates better waste management practices.',
    category: 'metrics',
    relatedTerms: ['circular-economy', 'zero-waste'],
    example: 'An event with 80% waste diversion sends only 20% of waste to landfills.'
  },
  {
    id: 'renewable-energy',
    term: 'Renewable Energy',
    definition: 'Energy from sources that naturally replenish, such as solar, wind, hydro, and geothermal. Using renewable energy for venue power significantly reduces carbon emissions.',
    category: 'recommendation',
    relatedTerms: ['carbon-footprint', 'venue-emissions'],
    example: 'Switching from grid power to solar can reduce venue emissions by 85%.'
  },
  {
    id: 'plant-based-catering',
    term: 'Plant-Based Catering',
    definition: 'Food and beverage options that exclude or minimize animal products. Plant-based meals have significantly lower carbon, water, and land footprints compared to meat-based options.',
    category: 'recommendation',
    relatedTerms: ['carbon-footprint', 'food-emissions'],
    example: 'A vegan meal produces 75% less emissions than a beef-based meal.'
  },
  {
    id: 'carbon-intensity',
    term: 'Carbon Intensity',
    definition: 'The amount of carbon emissions per unit of activity, such as kg CO2e per attendee or per dollar spent. Lower carbon intensity indicates more efficient resource use.',
    category: 'metrics',
    relatedTerms: ['carbon-footprint', 'efficiency-metrics'],
    example: 'Your event has a carbon intensity of 15 kg CO2e per attendee, 40% below industry average.'
  },
];

interface GlossaryProps {
  onClose?: () => void;
  initialFilter?: 'calculator' | 'recommendation' | 'metrics' | 'general' | 'all';
}

const Glossary: React.FC<GlossaryProps> = ({ onClose, initialFilter = 'all' }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [categoryFilter, setCategoryFilter] = useState<string>(initialFilter);
  const [expandedTerms, setExpandedTerms] = useState<Set<string>>(new Set());

  const categories = [
    { id: 'all', label: 'All Terms', count: GLOSSARY_TERMS.length },
    { id: 'calculator', label: 'Calculator', count: GLOSSARY_TERMS.filter(t => t.category === 'calculator').length },
    { id: 'recommendation', label: 'Recommendations', count: GLOSSARY_TERMS.filter(t => t.category === 'recommendation').length },
    { id: 'metrics', label: 'Metrics', count: GLOSSARY_TERMS.filter(t => t.category === 'metrics').length },
    { id: 'general', label: 'General', count: GLOSSARY_TERMS.filter(t => t.category === 'general').length },
  ];

  const filteredTerms = useMemo(() => {
    let terms = GLOSSARY_TERMS;

    // Filter by category
    if (categoryFilter !== 'all') {
      terms = terms.filter(t => t.category === categoryFilter);
    }

    // Filter by search query
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      terms = terms.filter(t =>
        t.term.toLowerCase().includes(query) ||
        t.definition.toLowerCase().includes(query) ||
        t.example?.toLowerCase().includes(query)
      );
    }

    return terms.sort((a, b) => a.term.localeCompare(b.term));
  }, [categoryFilter, searchQuery]);

  const toggleTerm = (termId: string) => {
    const newExpanded = new Set(expandedTerms);
    if (newExpanded.has(termId)) {
      newExpanded.delete(termId);
    } else {
      newExpanded.add(termId);
    }
    setExpandedTerms(newExpanded);
  };

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'calculator': return 'bg-emerald-100 text-emerald-700';
      case 'recommendation': return 'bg-amber-100 text-amber-700';
      case 'metrics': return 'bg-blue-100 text-blue-700';
      case 'general': return 'bg-purple-100 text-purple-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden max-w-4xl w-full max-h-[90vh] flex flex-col">
      {/* Header */}
      <div className="px-6 py-4 bg-gradient-to-r from-emerald-500 to-teal-500 text-white flex items-center justify-between">
        <div className="flex items-center gap-3">
          <BookOpen className="w-5 h-5" />
          <div>
            <h3 className="font-semibold text-lg">Sustainability Glossary</h3>
            <p className="text-emerald-100 text-sm">Key terms for calculators and recommendations</p>
          </div>
        </div>
        {onClose && (
          <button
            onClick={onClose}
            className="p-2 hover:bg-white/20 rounded-lg transition-colors"
            aria-label="Close glossary"
          >
            <X className="w-5 h-5" />
          </button>
        )}
      </div>

      {/* Search and Filters */}
      <div className="p-6 border-b border-gray-200 space-y-4">
        {/* Search */}
        <div className="relative">
          <Search className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search terms, definitions, examples..."
            className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>

        {/* Category Filters */}
        <div className="flex flex-wrap gap-2">
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => setCategoryFilter(cat.id)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                categoryFilter === cat.id
                  ? 'bg-emerald-500 text-white shadow-md'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {cat.label} <span className="opacity-70">({cat.count})</span>
            </button>
          ))}
        </div>
      </div>

      {/* Terms List */}
      <div className="flex-1 overflow-y-auto p-6">
        {filteredTerms.length === 0 ? (
          <div className="text-center py-12">
            <Info className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-500">No terms found matching your search.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {filteredTerms.map((term) => {
              const isExpanded = expandedTerms.has(term.id);
              return (
                <div
                  key={term.id}
                  className="border border-gray-200 rounded-xl overflow-hidden hover:border-emerald-300 transition-colors"
                >
                  <button
                    onClick={() => toggleTerm(term.id)}
                    className="w-full px-4 py-3 flex items-center justify-between bg-gray-50 hover:bg-gray-100 transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      <span className="font-semibold text-gray-900">{term.term}</span>
                      <span className={`px-2 py-0.5 rounded text-xs font-medium ${getCategoryColor(term.category)}`}>
                        {term.category}
                      </span>
                    </div>
                    {isExpanded ? (
                      <ChevronUp className="w-5 h-5 text-gray-400" />
                    ) : (
                      <ChevronDown className="w-5 h-5 text-gray-400" />
                    )}
                  </button>

                  {isExpanded && (
                    <div className="px-4 py-4 bg-white space-y-3">
                      <p className="text-gray-700 leading-relaxed">{term.definition}</p>

                      {term.example && (
                        <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3">
                          <p className="text-sm font-medium text-emerald-800 mb-1">Example:</p>
                          <p className="text-sm text-emerald-700">{term.example}</p>
                        </div>
                      )}

                      {term.relatedTerms && term.relatedTerms.length > 0 && (
                        <div>
                          <p className="text-sm font-medium text-gray-600 mb-2">Related Terms:</p>
                          <div className="flex flex-wrap gap-2">
                            {term.relatedTerms.map((relatedId) => {
                              const relatedTerm = GLOSSARY_TERMS.find(t => t.id === relatedId);
                              return relatedTerm ? (
                                <button
                                  key={relatedId}
                                  onClick={() => {
                                    toggleTerm(relatedId);
                                    // Scroll to the related term
                                    setTimeout(() => {
                                      const element = document.getElementById(`term-${relatedId}`);
                                      element?.scrollIntoView({ behavior: 'smooth', block: 'center' });
                                    }, 100);
                                  }}
                                  className="px-3 py-1 bg-white border border-gray-300 rounded-lg text-sm text-gray-700 hover:border-emerald-500 hover:text-emerald-700 transition-colors"
                                >
                                  {relatedTerm.term}
                                </button>
                              ) : null;
                            })}
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-6 py-3 bg-gray-50 border-t border-gray-200 text-center">
        <p className="text-sm text-gray-600">
          Showing <strong>{filteredTerms.length}</strong> of <strong>{GLOSSARY_TERMS.length}</strong> terms
        </p>
      </div>
    </div>
  );
};

export default Glossary;

